apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-p
  namespace: argo-system
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-system
  project: default
  source:
    path: helm-values/redis/
    plugin:
      env:
        - name: CHART_VERSION
          value: "10.5.7"
        - name: VALUE_FILE_NAME
          value: "prod.values.yaml"
        - name: CHART_NAME
          value: redis
      name: helm-resolver
    repoURL: https://github.com/hschoi1104/argo-rollout-test/
