apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kustomize-helm-sample-prod
  namespace: argo-system
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argo-system
    name: in-cluster
  project: default
  source:
    path: kustomize-helm-app-of-apps
    repoURL: https://github.com/hschoi1104/argo-rollouts-test
    targetRevision: HEAD
    plugin:
      name: kustomized-helm