---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argo-system
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  configManagementPlugins: |
    - name: kustomized-helm
      init:
        command: ["/bin/sh", "-c"]
        args: ["helm dependency build || true"]
      generate:
        command: ["/bin/sh", "-c"]
        args: ["helm template ../../helm_base --name-template $ARGOCD_APP_NAME --include-crds > ../../helm_base/all.yml && kustomize build"]
    - name: helm-resolver
      init:
        command: [bash, -c]
        args: ["helm repo add test-repo https://hschoi1104.github.io/helm-chart/stable"]
      generate:
        command: [bash, -c]
        args: ["helm template -n argo-system --values $VALUE_FILE_NAME $ARGOCD_APP_NAME redis --version $CHART_VERSION"]
