apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-app-of-apps
  namespace: argo-system
spec:
  project: default
  source:
    repoURL: https://github.com/modusign/applications.git
    targetRevision: HEAD
    path: example/helm-app-of-apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-system