apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: shared-
bases:
- ../../helm_base

namespace: shared
commonLabels:
  app.kubernetes.io/part-of: argocd-app-of-apps-example
  app.kubernetes.io/managed-by: argocd


resources:
- namespace.yml
