apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-stage
  namespace: argo-system
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.env }}
  project: default
  source:
    repoURL: https://github.com/hschoi1104/helm-chart/
    path: values
    plugin:
      env:
        - name: CHART_VERSION
          value: "10.5.7"
        - name: VALUE_FILE_NAME
          value: "./stage/redis-values.yaml"
        - name: CHART_NAME
          value: redis
      name: helm-resolver
