apiVersion: v1
kind: Secret
metadata:
  name: aws-example
  annotations:
    avp.kubernetes.io/path: "shared/vault/test" # The name of your AWS Secret
stringData:
  sample-secret: <vault_test_key>
type: Opaque